-- HQS Admin schema initial
create table if not exists public.roles (id uuid primary key default gen_random_uuid(), name text unique not null, permissions jsonb not null default '{}'::jsonb);
create table if not exists public.agents (id uuid primary key default gen_random_uuid(), user_id uuid unique, role_id uuid references public.roles(id), full_name text not null, email text unique, phone text, status text not null default 'ACTIVE', created_at timestamptz not null default now());
create table if not exists public.clients (id uuid primary key default gen_random_uuid(), full_name text not null, email text, phone text, budget_min numeric, budget_max numeric, preferences jsonb not null default '{}'::jsonb, status text not null default 'ACTIVE', created_at timestamptz not null default now());
create table if not exists public.properties (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, description text, type text, transaction text, price numeric, surface numeric, rooms int, baths int, floor int, year_built int, address text, zone text, sector text, lat numeric, lng numeric, status text not null default 'DRAFT', featured boolean not null default false, agent_id uuid references public.agents(id), meta_title text, meta_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.property_images (id uuid primary key default gen_random_uuid(), property_id uuid references public.properties(id) on delete cascade, url text not null, sort_order int not null default 0, alt text);
create table if not exists public.leads (id uuid primary key default gen_random_uuid(), name text not null, email text, phone text not null, source text, status text not null default 'NEW', property_id uuid references public.properties(id), assigned_agent_id uuid references public.agents(id), last_contact_at timestamptz, next_follow_up_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.lead_notes (id uuid primary key default gen_random_uuid(), lead_id uuid references public.leads(id) on delete cascade, note text not null, author_id uuid, created_at timestamptz not null default now());
create table if not exists public.appointments (id uuid primary key default gen_random_uuid(), lead_id uuid references public.leads(id), client_id uuid references public.clients(id), property_id uuid references public.properties(id), agent_id uuid references public.agents(id), start_at timestamptz not null, end_at timestamptz not null, status text not null default 'SCHEDULED', reminder_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.website_sections (id uuid primary key default gen_random_uuid(), page_key text not null, section_key text not null, content jsonb not null default '{}'::jsonb, published boolean not null default false, updated_at timestamptz not null default now());
create table if not exists public.seo_pages (id uuid primary key default gen_random_uuid(), page_key text unique not null, meta_title text, meta_description text, og_image text, noindex boolean not null default false, schema_json jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists public.analytics_events (id uuid primary key default gen_random_uuid(), event_name text not null, entity_type text, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid, action text not null, entity_type text, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.settings (key text primary key, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
