name = "imobiliare2"
compatibility_date = "2026-05-17"

[[d1_databases]]
binding = "DB"
database_name = "imobiliare-db"
database_id = "bcd78e0d-6aeb-4a79-8b2d-7ac59fd15e29"

[vars]
NODE_VERSION = "20"
node_version = "20"
