name = "hqs-imobiliare"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "hqs-imobiliare-db"
database_id = "96fa755c-4fdf-4d45-98f3-933fedb4a97e"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://spmapzhlcwhzfrxuvgxd.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_24oJXCI0JLY1VyLq_Ls-AA_-tYFf729"
